# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

version: "2"
virtualmachines:
- name: workstation
  image: instruqt-hashicorp/developing-apps-with-vault
  shell: /bin/bash
  machine_type: g1-small
